apiVersion: apps/v1
kind: Deployment
metadata:
  name: ginger-reservation-app
  labels:
    app: ginger-reservation-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ginger-reservation-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ginger-reservation-app
    spec:
      containers:
        - name: ginger-reservation-app
          image: ayushshaha1008/ginger-reservation:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
